services:
  resonate:
    platform: linux/amd64
    build: .
    image: resonate:latest
    stdin_open: true
    tty: true
    environment:
      - PLEX_URL=${PLEX_URL:-http://localhost:32400}
      - PLEX_TOKEN=${PLEX_TOKEN:-}
    network_mode: host
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./data:/app/data
      - ./models:/app/models
      # Media volume mount:
      - /data/music:/data/music
