"""Taxonomy and mood decision engine package for Resonate."""

from resonate.engine.mood_rules import (
    DEFAULT_GENRE_EXCLUSIONS,
    DEFAULT_GENRE_MOOD_SEEDS,
    DEFAULT_MOOD_CONFLICTS,
    DEFAULT_MOOD_TAGS,
    DEFAULT_TARGET_MOODS,
    apply_bpm_mood_rules,
    get_genre_seeded_moods,
    is_mood_excluded_by_genre,
    is_valid_mood_tag,
    resolve_mood_conflicts,
    synthesize_track_moods,
)
from resonate.engine.pipeline import EnrichmentPipeline
from resonate.engine.tag_filter import (
    BOILERPLATE_TAGS,
    GENRE_KEYWORDS,
    RECOGNIZED_MOOD_KEYWORDS,
    is_artist_or_album_match,
    is_boilerplate_tag,
)
from resonate.engine.taxonomy import (
    DEFAULT_PRIMARY_GENRES,
    DEFAULT_SUB_GENRES,
    GENERIC_MODIFIERS,
    MUTUALLY_EXCLUSIVE_STYLES,
    NATIONALITY_STRINGS,
    PRIMARY_GENRE_STEMS,
    SUB_GENRE_STEMS,
    SUBGENRE_REGISTRY,
    SUBGENRE_TO_FAMILY,
    SubgenreSpec,
    deduplicate_subgenres,
    filter_subgenres_by_family,
    is_valid_subgenre_tag,
    promote_genre_by_subgenres,
)
from resonate.engine.tracer import DecisionTracer

__all__ = [
    "BOILERPLATE_TAGS",
    "DEFAULT_GENRE_EXCLUSIONS",
    "DEFAULT_GENRE_MOOD_SEEDS",
    "DEFAULT_MOOD_CONFLICTS",
    "DEFAULT_MOOD_TAGS",
    "DEFAULT_PRIMARY_GENRES",
    "DEFAULT_SUB_GENRES",
    "DEFAULT_TARGET_MOODS",
    "DecisionTracer",
    "EnrichmentPipeline",
    "GENERIC_MODIFIERS",
    "GENRE_KEYWORDS",
    "MUTUALLY_EXCLUSIVE_STYLES",
    "NATIONALITY_STRINGS",
    "PRIMARY_GENRE_STEMS",
    "RECOGNIZED_MOOD_KEYWORDS",
    "SUBGENRE_REGISTRY",
    "SUBGENRE_TO_FAMILY",
    "SUB_GENRE_STEMS",
    "SubgenreSpec",
    "apply_bpm_mood_rules",
    "deduplicate_subgenres",
    "filter_subgenres_by_family",
    "get_genre_seeded_moods",
    "is_artist_or_album_match",
    "is_boilerplate_tag",
    "is_mood_excluded_by_genre",
    "is_valid_mood_tag",
    "is_valid_subgenre_tag",
    "promote_genre_by_subgenres",
    "resolve_mood_conflicts",
    "synthesize_track_moods",
]
