"""Taxonomy and mood decision engine package for Resonate."""

from resonate.engine.mood_rules import (
    DEFAULT_MOOD_TAGS,
    DEFAULT_TARGET_MOODS,
    GENRE_MOOD_SEEDS,
    MUTUALLY_EXCLUSIVE_MOODS,
    apply_bpm_mood_rules,
    get_genre_seeded_moods,
    is_valid_mood_tag,
    resolve_mood_conflicts,
    synthesize_track_moods,
)
from resonate.engine.taxonomy import (
    DEFAULT_PRIMARY_GENRES,
    DEFAULT_SUB_GENRES,
    GENERIC_MODIFIERS,
    MUTUALLY_EXCLUSIVE_STYLES,
    NATIONALITY_STRINGS,
    PRIMARY_GENRE_STEMS,
    SUB_GENRE_STEMS,
    SUBGENRE_TO_FAMILY,
    deduplicate_subgenres,
    is_valid_subgenre_tag,
    promote_genre_by_subgenres,
    sanitize_subgenres_for_genre,
)

__all__ = [
    "DEFAULT_MOOD_TAGS",
    "DEFAULT_PRIMARY_GENRES",
    "DEFAULT_SUB_GENRES",
    "DEFAULT_TARGET_MOODS",
    "GENERIC_MODIFIERS",
    "GENRE_MOOD_SEEDS",
    "MUTUALLY_EXCLUSIVE_MOODS",
    "MUTUALLY_EXCLUSIVE_STYLES",
    "NATIONALITY_STRINGS",
    "PRIMARY_GENRE_STEMS",
    "SUBGENRE_TO_FAMILY",
    "SUB_GENRE_STEMS",
    "apply_bpm_mood_rules",
    "deduplicate_subgenres",
    "get_genre_seeded_moods",
    "is_valid_mood_tag",
    "is_valid_subgenre_tag",
    "promote_genre_by_subgenres",
    "resolve_mood_conflicts",
    "sanitize_subgenres_for_genre",
    "synthesize_track_moods",
]
